# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOiwEuJ6wm6gAkCvueTuZkmkyfJUp5zb
"""

import streamlit as st
import numpy as np
import joblib

# تحميل الموديل
model = joblib.load('heart_disease_model.pkl')
scaler = joblib.load('scaler.pkl')

st.set_page_config(page_title="AI Healthcare Diagnostic Assistant")

st.title("❤️ AI Healthcare Diagnostic Assistant")
st.write("Heart Disease Prediction System")

st.sidebar.header("Patient Information")

def user_input():
    age = st.sidebar.slider('Age', 20, 80, 50)
    sex = st.sidebar.selectbox('Sex', [0, 1])  # 0: Female, 1: Male
    cp = st.sidebar.selectbox('Chest Pain Type (0-3)', [0,1,2,3])
    trestbps = st.sidebar.slider('Resting Blood Pressure', 80, 200, 120)
    chol = st.sidebar.slider('Cholesterol', 100, 400, 200)
    fbs = st.sidebar.selectbox('Fasting Blood Sugar > 120 mg/dl', [0,1])
    restecg = st.sidebar.selectbox('Rest ECG (0-2)', [0,1,2])
    thalach = st.sidebar.slider('Max Heart Rate', 60, 220, 150)
    exang = st.sidebar.selectbox('Exercise Induced Angina', [0,1])
    oldpeak = st.sidebar.slider('ST Depression', 0.0, 6.0, 1.0)
    slope = st.sidebar.selectbox('Slope (0-2)', [0,1,2])
    ca = st.sidebar.slider('Major Vessels (0-3)', 0, 3, 0)
    thal = st.sidebar.selectbox('Thal (1 = normal, 2 = fixed, 3 = reversible)', [1,2,3])

    data = np.array([[age, sex, cp, trestbps, chol, fbs, restecg,
                      thalach, exang, oldpeak, slope, ca, thal]])
    return data

input_data = user_input()

# Scaling
input_scaled = scaler.transform(input_data)

if st.button("Predict"):
    prediction = model.predict(input_scaled)

    if prediction[0] == 1:
        st.error("⚠️ Heart Disease Detected. Please consult a doctor.")
    else:
        st.success("✅ No Heart Disease Detected.")